sudo: false

language: php

php:
    - 7.2

matrix:
    include:
        - name: Lowest dependency versions
          php: 7.2
          env: dependencies=lowest

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini
    - phpenv config-add .travis/php.ini

install:
    - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --classmap-authoritative --no-suggest --prefer-lowest --prefer-stable; else travis_retry composer install --classmap-authoritative --no-suggest --prefer-dist; fi

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs
